import type { FavoriteItem } from "./favoritesTypes";

export interface PromptTemplate {
  id: string;
  label: string;
  description: string;
  starter: {
    label: string;
    note: string;
    promptTemplate: string;
    targetOverride: FavoriteItem["targetOverride"];
    pasteAfterOpen: boolean;
  };
}

export const PROMPT_TEMPLATES: PromptTemplate[] = [
  {
    id: "blank",
    label: "Blank Prompt",
    description: "Start from an empty prompt template",
    starter: {
      label: "New Prompt",
      note: "",
      promptTemplate: [
        "// Start typing your own prompt below.",
        "// The lines here are just examples of the available keywords/tokens.",
        "// Delete or modify them as you like.",
        "",
        "// Supported tokens:",
        "//   ${input}                  — ask for a single value",
        "//   ${input:Label here}      — ask with a custom label",
        "//   ${selection}             — current editor selection",
        "//   ${file}                  — full path to current file",
        "//   ${relativePath}          — path relative to workspace root",
        "//   ${workspaceFolder}       — workspace root path",
        "//   ${clipboard}             — current clipboard text",
        "",
        "// Example:",
        "// You are an expert software engineer.",
        "//",
        "// Task:",
        "// ${input:What do you want to do?}",
        "//",
        "// Context:",
        "// - File: ${file}",
        "// - Relative: ${relativePath}",
        "// - Workspace: ${workspaceFolder}",
        "//",
        "// Selected code:",
        "// ${selection}",
        "//",
        "// Clipboard (if relevant):",
        "// ${clipboard}",
      ].join("\n"),
      targetOverride: "auto",
      pasteAfterOpen: true,
    },
  },
  {
    id: "explain-selection",
    label: "Explain Selection",
    description: "Explain selected code with context",
    starter: {
      label: "Explain selection with context",
      note: "Explains the selected code and surrounding context",
      promptTemplate: [
        "You are an expert software engineer.",
        "",
        "Task:",
        "${input:What do you want explained?}",
        "",
        "Current file path: ${file}",
        "Relative to workspace: ${relativePath}",
        "Workspace root: ${workspaceFolder}",
        "",
        "Selected code:",
        "${selection}",
        "",
        "Clipboard (if relevant):",
        "${clipboard}",
        "",
        "Please respond with:",
        "- A clear explanation",
        "- Important dependencies or assumptions",
        "- Any issues or improvements",
      ].join("\n"),
      targetOverride: "auto",
      pasteAfterOpen: true,
    },
  },
  {
    id: "planning",
    label: "Planning Prompt",
    description: "Create a markdown implementation plan with decisions, pros/cons, and recommendation",
    starter: {
      label: "Create markdown implementation plan",
      note: "Planning-only prompt. Produces a markdown plan with checklist, decisions, pros/cons, and recommendations.",
      promptTemplate: [
        "You are an expert software engineer.",
        "",
        "The user wants a planning response only. Do not implement anything yet.",
        "",
        "Plan title:",
        "${input:What should the plan be called?}",
        "",
        "Change request:",
        "${input:What change are you planning?}",
        "",
        "Context:",
        "- Current file: ${file}",
        "- Relative path: ${relativePath}",
        "- Workspace root: ${workspaceFolder}",
        "",
        "Selected code:",
        "${selection}",
        "",
        "Clipboard context (if relevant):",
        "${clipboard}",
        "",
        "Create a dedicated markdown FILE in the workspace for this plan instead of inlining the full document in chat.",
        "- Choose a clear name based on the plan title and change request.",
        "- If you cannot safely write a file, explain that and fall back to returning the full markdown in chat.",
        "",
        "The markdown document must include:",
        "",
        "# <Plan Title>",
        "",
        "## Goal",
        "",
        "## Current Context",
        "",
        "## Scope",
        "### In Scope",
        "### Out of Scope",
        "",
        "## Implementation Checklist",
        "Restate the final implementation plan as a numbered checklist.",
        "",
        "## Decisions",
        "For each important decision, use this exact structure:",
        "",
        "1. Decision X",
        "   - Option A: <short description>",
        "     - Pros: <why>",
        "     - Cons: <why>",
        "   - Option B: <short description>",
        "     - Pros: <why>",
        "     - Cons: <why>",
        "   - (Option C if useful, same pattern as above)",
        "   - Recommendation: <which option and why>",
        "",
        "Then provide:",
        "1. The files or modules likely to change",
        "2. The invariants that must remain true (things that must NOT change)",
        "3. Any assumptions you are making",
        "4. Risks or tricky areas",
        "5. Validation steps that will confirm the implementation worked",
        "",
        "Ask any clarifying questions as warranted.",
        "",
        "Do not implement anything yet.",
        "",
        "In your chat response, do NOT paste the entire markdown plan.",
        "- Confirm the file path where you wrote the plan.",
        "- Provide a very short summary and a link or instructions to open the markdown file.",
      ].join("\n"),
      targetOverride: "auto",
      pasteAfterOpen: true,
    },
  },
  {
    id: "review-selection",
    label: "Review Selection",
    description: "Review selected code for issues and improvements",
    starter: {
      label: "Review selection",
      note: "Reviews selected code for bugs, maintainability, and improvements",
      promptTemplate: [
        "You are an expert software engineer performing a code review.",
        "",
        "Review goal:",
        "${input:What kind of review do you want?}",
        "",
        "Current file path: ${file}",
        "Relative to workspace: ${relativePath}",
        "",
        "Selected code:",
        "${selection}",
        "",
        "Please provide:",
        "1. Overall assessment",
        "2. Bugs or correctness issues",
        "3. Maintainability concerns",
        "4. Performance concerns",
        "5. Suggested improvements",
      ].join("\n"),
      targetOverride: "auto",
      pasteAfterOpen: true,
    },
  },
  {
    id: "debug-issue",
    label: "Debug Issue",
    description: "Diagnose a bug or unexpected behavior from selected code",
    starter: {
      label: "Debug issue from selection",
      note: "Helps diagnose likely causes and debugging steps",
      promptTemplate: [
        "You are an expert software engineer helping diagnose a bug.",
        "",
        "Problem:",
        "${input:What problem or symptom are you seeing?}",
        "",
        "Current file path: ${file}",
        "Relative to workspace: ${relativePath}",
        "",
        "Selected code:",
        "${selection}",
        "",
        "Clipboard context (if relevant):",
        "${clipboard}",
        "",
        "Please provide:",
        "1. Most likely causes",
        "2. What to inspect first",
        "3. Specific debugging steps",
        "4. Any assumptions or missing information",
      ].join("\n"),
      targetOverride: "auto",
      pasteAfterOpen: true,
    },
  },
];

